### PR TITLE
Right + left hand trials and screenshots

### PR DESCRIPTION
**Pull request by juddyf**
^^

### CODE REVIEW

**Review by emmer13 — APPROVED** [review]

**Review by bbwong23 — CHANGES_REQUESTED** [review]
limit to at most 2 trials on each hand. Currently seems to be going on forever

**Review by ccharyi — CHANGES_REQUESTED** [review]
LGTM, but it doesn't seem like there is any indication that the test has been completed. Maybe hide / disable the canvas and image and switch the save text button to "start testing!". Same for when the user first enters the page

**Comment by juddyf** [comment]
@bbwong23 we don't have an end screen yet since we haven't figured out how to score the drawing, so i just set up some framework that'll make it take us to the end screen and we can work on that later. That's not required for today right?
@ccharyi sounds like another task:
screen shot 2017-02-14 at 12 56 22 pm

**Comment by ccharyi** [comment]
@juddyf ok, it looks very similar to the  task assigned to @skoy7
LGTM

**Review by ccharyi — APPROVED** [review]

**Review by bbwong23 — APPROVED** [review]

**Pull request merged**
